"""Deploy Host MCP Python app to hosting.com (Passenger via cloudlinux-selector)."""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

from host.config import load_env
from host.deploy import _ssh_argv, _ssh_target
from host.manifest import SiteManifest

APP_ROOT = "host-mcp"
APP_URI = "host"
PYTHON_VERSION = "3.11.15"
WORKSPACE = Path("/home/ken/ws")

PACKAGE_DIRS = {
    "host": WORKSPACE / "host",
    "cmdline": WORKSPACE / "shared" / "cmdline",
    "ken-mcp": WORKSPACE / "shared" / "mcp",
    "util": WORKSPACE / "util",
}

RSYNC_EXCLUDES = [
    ".git",
    ".venv",
    "__pycache__",
    "*.pyc",
    ".pytest_cache",
    ".mypy_cache",
]


def _identity_rsync_args() -> list[str]:
    identity = os.environ.get("HOST_SSH_IDENTITY_FILE", "").strip()
    if identity:
        return ["-e", f"ssh -i {identity} -o IdentitiesOnly=yes -o BatchMode=yes"]
    return ["-e", "ssh -o BatchMode=yes"]


def _rsync_local(local: Path, remote_target: str, *, delete: bool = True) -> int:
    args = ["rsync", "-az", *_identity_rsync_args(), "--human-readable"]
    if delete:
        args.append("--delete")
    for pattern in RSYNC_EXCLUDES:
        args.extend(["--exclude", pattern])
    args.extend([f"{local}/", remote_target])
    return subprocess.run(args, check=False).returncode


def _ssh_run(manifest: SiteManifest, command: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(_ssh_argv(command, manifest), check=False, text=True, capture_output=True)


def _mcp_env_vars() -> dict[str, str]:
    load_env()
    keys = [
        "HOST_MCP_BASE_URL",
        "HOST_MCP_CLIENT_ID",
        "HOST_MCP_CLIENT_SECRET",
        "HOST_MCP_HOST",
        "HOST_MCP_PORT",
        "HOST_SSH_USER",
        "HOST_SSH_HOST",
    ]
    return {k: v for k in keys if (v := os.environ.get(k, "").strip())}


def _server_requirements() -> str:
    return """# Generated by sitehost deploy-mcp
fastmcp>=2.0.0
mcp>=1.0.0
python-dotenv>=1.0.0
pyyaml>=6.0.0
tqdm>=4.66.0
a2wsgi>=1.10.0
-e src/host
-e src/cmdline
-e src/ken-mcp
-e src/util
"""


def _sync_config(manifest: SiteManifest, ssh_target: str) -> None:
    config_dir = Path.home() / ".config" / "ken" / "host"
    _ssh_run(manifest, "mkdir -p ~/.config/ken/host")
    for name in ("host.env", "sites.yaml", "domains.yaml", "deploy_key"):
        local = config_dir / name
        if local.is_file():
            subprocess.run(
                ["rsync", "-az", *_identity_rsync_args(), str(local), f"{ssh_target}:.config/ken/host/{name}"],
                check=False,
            )
    _ssh_run(manifest, "chmod 600 ~/.config/ken/host/deploy_key 2>/dev/null || true")
    _ssh_run(manifest, "chmod 600 ~/.config/ken/host/host.env 2>/dev/null || true")


def deploy_mcp(
    manifest: SiteManifest,
    *,
    dry_run: bool = False,
    domain: str | None = None,
) -> int:
    """Rsync Host MCP app + deps, register Passenger app, install venv packages."""
    site_domain = domain or manifest.domain
    ssh_target = _ssh_target(manifest)
    remote_app = f"~/{APP_ROOT}"

    template_dir = Path(__file__).resolve().parents[2] / "templates" / "python-app"
    if not template_dir.is_dir():
        print(f"Missing template: {template_dir}", file=sys.stderr)
        return 1

    env_vars = _mcp_env_vars()
    if not env_vars.get("HOST_MCP_CLIENT_SECRET"):
        print("HOST_MCP_CLIENT_SECRET not set. Run: sitehost setup-deploy --ssh-user USER", file=sys.stderr)
        return 1

    if dry_run:
        print(f"Dry-run: would deploy Host MCP to {site_domain}/{APP_URI}")
        print(f"  App root: {remote_app}")
        print(f"  Python: {PYTHON_VERSION}")
        print(f"  Packages: {', '.join(PACKAGE_DIRS)}")
        print(f"  Env keys: {', '.join(env_vars)}")
        return 0

    print(f"Syncing python-app template → {ssh_target}:{remote_app}/")
    if _rsync_local(template_dir, f"{ssh_target}:{remote_app}/", delete=False) != 0:
        return 1

    _ssh_run(manifest, f"mkdir -p ~/{APP_ROOT}/src")

    for name, local in PACKAGE_DIRS.items():
        if not local.is_dir():
            print(f"Missing package dir: {local}", file=sys.stderr)
            return 1
        dest = f"{ssh_target}:{remote_app}/src/{name}/"
        print(f"Syncing {name} → {dest}")
        if _rsync_local(local, dest) != 0:
            return 1

    _sync_config(manifest, ssh_target)

    req_body = _server_requirements()
    remote_script = f"""
set -e
mkdir -p ~/{APP_ROOT}
cat > ~/{APP_ROOT}/requirements-deploy.txt << 'REQEOF'
{req_body}REQEOF

APP_EXISTS=$(cloudlinux-selector get --json --interpreter python --domain {site_domain} 2>/dev/null | grep -c '"{APP_ROOT}"' || true)
if [ "$APP_EXISTS" = "0" ]; then
  cloudlinux-selector create --json --interpreter python \\
    --domain {site_domain} \\
    --app-root {APP_ROOT} \\
    --app-uri {APP_URI} \\
    --version {PYTHON_VERSION} \\
    --startup-file passenger_wsgi.py \\
    --entry-point application
else
  echo "Python app {APP_ROOT} already registered"
fi

cloudlinux-selector install-modules --json --interpreter python \\
  --domain {site_domain} --app-root {APP_ROOT} --requirements-file ~/{APP_ROOT}/requirements-deploy.txt --skip-web-check || \\
  (source ~/virtualenv/{APP_ROOT}/3.11/bin/activate && cd ~/{APP_ROOT} && pip install -r requirements-deploy.txt)

cloudlinux-selector restart --json --interpreter python \\
  --domain {site_domain} --app-root {APP_ROOT}

echo "OK — test: curl -sI https://{site_domain}/{APP_URI}/mcp"
"""

    print(f"Running remote setup on {ssh_target}...")
    result = _ssh_run(manifest, remote_script)
    if result.stdout:
        print(result.stdout)
    if result.returncode != 0:
        if result.stderr:
            print(result.stderr, file=sys.stderr)
        return result.returncode

    print(f"\nVerify: curl -sI https://{site_domain}/{APP_URI}/mcp")
    return 0
