"""Bootstrap deploy keys, host.env, and GitHub Actions secrets."""

from __future__ import annotations

import secrets
import subprocess
import sys
from pathlib import Path

CONFIG_DIR = Path.home() / ".config" / "ken" / "host"
DEPLOY_KEY = CONFIG_DIR / "deploy_key"
DEPLOY_KEY_PUB = CONFIG_DIR / "deploy_key.pub"
HOST_ENV = CONFIG_DIR / "host.env"
ENV_EXAMPLE = Path(__file__).resolve().parents[2] / "docs" / "host.env.example"


def _run(cmd: list[str], *, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, capture_output=True, text=True, check=check)


def ensure_deploy_key(force: bool = False) -> tuple[Path, Path]:
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    if DEPLOY_KEY.exists() and DEPLOY_KEY_PUB.exists() and not force:
        return DEPLOY_KEY, DEPLOY_KEY_PUB
    if DEPLOY_KEY.exists() and force:
        DEPLOY_KEY.unlink(missing_ok=True)
        DEPLOY_KEY_PUB.unlink(missing_ok=True)
    _run(
        [
            "ssh-keygen",
            "-t",
            "ed25519",
            "-f",
            str(DEPLOY_KEY),
            "-N",
            "",
            "-C",
            "ken-host-deploy",
        ]
    )
    DEPLOY_KEY.chmod(0o600)
    return DEPLOY_KEY, DEPLOY_KEY_PUB


def ensure_host_env(
    *,
    ssh_user: str | None = None,
    ssh_host: str = "seehart.com",
    force_secret: bool = False,
) -> Path:
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    client_secret = secrets.token_urlsafe(32)
    if HOST_ENV.exists() and not force_secret:
        text = HOST_ENV.read_text()
        for line in text.splitlines():
            if line.startswith("HOST_MCP_CLIENT_SECRET=") and not line.endswith("change-me"):
                client_secret = line.split("=", 1)[1]
                break

    user = ssh_user or "YOUR_CPANEL_USER"
    body = f"""# Host MCP + deploy — generated by sitehost setup-deploy

HOST_MCP_BASE_URL=https://seehart.com/host
HOST_MCP_CLIENT_ID=host-mcp
HOST_MCP_CLIENT_SECRET={client_secret}
HOST_MCP_HOST=0.0.0.0
HOST_MCP_PORT=8754

HOST_SSH_USER={user}
HOST_SSH_HOST={ssh_host}
HOST_SSH_IDENTITY_FILE={DEPLOY_KEY}
"""
    HOST_ENV.write_text(body)
    HOST_ENV.chmod(0o600)
    return HOST_ENV


def print_setup_instructions(
    *,
    repo: str = "kenseehart/seehart",
    ssh_user: str | None = None,
    ssh_host: str = "seehart.com",
) -> None:
    ensure_deploy_key()
    ensure_host_env(ssh_user=ssh_user, ssh_host=ssh_host)
    user = ssh_user or "YOUR_CPANEL_USER"
    pub = DEPLOY_KEY_PUB.read_text().strip()

    print("Host deploy bootstrap")
    print("====================")
    print()
    print("1. Add this public key to hosting.com → SSH Access → Manage SSH Keys:")
    print()
    print(pub)
    print()
    print("2. SSH discovery (replace user if needed):")
    print(f"   ssh -i {DEPLOY_KEY} {user}@{ssh_host} 'ls -la ~/public_html'")
    print()
    print("3. WordPress backup before first deploy:")
    print(
        f"   ssh -i {DEPLOY_KEY} {user}@{ssh_host} "
        "'tar czf ~/wp-backup-$(date +%Y%m%d).tar.gz -C ~/public_html .'"
    )
    print()
    print("4. Export env for local deploy:")
    print(f"   set -a && source {HOST_ENV} && set +a")
    print()
    print("5. GitHub Actions secrets (requires gh auth with admin:repo):")
    print(f"   gh secret set SSH_PRIVATE_KEY --repo {repo} < {DEPLOY_KEY}")
    print(f"   gh secret set HOST_SSH_USER --repo {repo} --body '{user}'")
    print(f"   gh secret set HOST_SSH_HOST --repo {repo} --body '{ssh_host}'")
    print()
    print("6. Dry-run deploy:")
    print("   sitehost deploy --manifest /home/ken/ws/seehart/host.yaml --dry-run")
    print()
    print(f"Config: {HOST_ENV}")
    print(f"Deploy key: {DEPLOY_KEY}")


def apply_github_secrets(
    *,
    repo: str,
    ssh_user: str,
    ssh_host: str,
) -> int:
    ensure_deploy_key()
    errors = 0
    for name, value, path in [
        ("SSH_PRIVATE_KEY", None, DEPLOY_KEY),
        ("HOST_SSH_USER", ssh_user, None),
        ("HOST_SSH_HOST", ssh_host, None),
    ]:
        cmd = ["gh", "secret", "set", name, "--repo", repo]
        if path:
            cmd.extend(["<", str(path)])
            result = subprocess.run(
                f"gh secret set {name} --repo {repo} < {path}",
                shell=True,
                capture_output=True,
                text=True,
            )
        else:
            result = subprocess.run(
                ["gh", "secret", "set", name, "--repo", repo, "--body", value],
                capture_output=True,
                text=True,
            )
        if result.returncode != 0:
            print(f"gh secret set {name}: {result.stderr.strip()}", file=sys.stderr)
            errors += 1
        else:
            print(f"Set secret {name} on {repo}")
    return 1 if errors else 0
